"""Export to a runnable pytest module, so a flow can gate CI.

"Runnable" is a claim worth being careful about. An earlier version of this
exporter emitted calls to a ``pf.target(...)`` helper that no generated file ever
imported, so the module compiled cleanly and then died with ``NameError`` the
moment it ran -- the worst kind of export, since ``compile()`` in a test suite
passes and nothing looks wrong until CI.

So targets are emitted as plain dict literals with no helper to import, and the
result carries a ``conftest.py`` skeleton defining the one fixture the module
needs. What that fixture must provide is stated in the file rather than implied.
"""

from __future__ import annotations

import json

from pixelforge.exporters.base import ExportResult, ExportWarning
from pixelforge.script.model import Project, Script, Step, StepAction, Target

__all__ = ["PytestExporter"]

_MODULE_HEADER = '''"""Generated by PixelForge from {script_name!r}. Do not edit by hand.

Re-export from PixelForge after changing the flow; edits here are lost.

Targets are plain dicts in PixelForge's Target shape. The `pf_device` fixture is
what binds them to a real phone -- see conftest.py.
"""

import pytest

pytestmark = [pytest.mark.asyncio, pytest.mark.device]


'''

_CONFTEST = '''"""Fixture contract for PixelForge-generated tests.

The generated modules call exactly the methods below. Implement them against
whatever drives your devices in CI -- PixelForge's own ScriptRunner, Appium, or a
thin adb wrapper -- and the exported flows run unchanged.

Each `target` argument is a dict in PixelForge's Target shape::

    {"strategy": ["a11y", "template", "ocr", "coord"],
     "a11y": {"resource_id": "..."},
     "template": {"file": "pay.png", "threshold": 0.9},
     "ocr": {"pattern": "Total"},
     "coord": {"x": 0.5, "y": 0.9}}

Honour `strategy` as an ordered fallback chain rather than picking one field: that
ordering is what lets one flow run on a device with an accessibility tree and on a
game canvas without one.
"""

import pytest


class PixelForgeDevice:
    """Adapt this to your runner."""

    async def tap(self, target: dict) -> None:
        raise NotImplementedError

    async def long_press(self, target: dict, duration_ms: int) -> None:
        raise NotImplementedError

    async def swipe(self, target: dict, to: tuple[float, float], duration_ms: int) -> None:
        raise NotImplementedError

    async def input_text(self, target: dict, text: str) -> None:
        raise NotImplementedError

    async def key(self, keycode: int) -> None:
        raise NotImplementedError

    async def launch_app(self, package: str) -> None:
        raise NotImplementedError

    async def stop_app(self, package: str) -> None:
        raise NotImplementedError

    async def wait_for(self, target: dict, timeout_ms: int) -> None:
        raise NotImplementedError

    async def exists(self, target: dict) -> bool:
        raise NotImplementedError

    async def screenshot(self, label: str) -> None:
        raise NotImplementedError

    async def sleep(self, seconds: float) -> None:
        raise NotImplementedError


@pytest.fixture
async def pf_device() -> PixelForgeDevice:
    return PixelForgeDevice()
'''


class PytestExporter:
    name = "pytest"
    description = "A pytest module plus a conftest skeleton, to replay the flow in CI"

    def export(self, project: Project, script: Script) -> ExportResult:
        warnings: list[ExportWarning] = []
        lines: list[str] = []
        func = _identifier(script.id)

        lines.append(f"async def test_{func}(pf_device):")
        lines.append(f'    """{script.name}"""')
        enabled = [step for step in script.steps if step.enabled]
        if not enabled:
            lines.append("    pytest.skip('script has no enabled steps')")

        for step in script.steps:
            if not step.enabled:
                lines.append(f"    # skipped (disabled): {step.name}")
                continue
            lines.append(f"    # {step.name}")
            lines.extend(f"    {line}" for line in self._emit(step, warnings))
        lines.append("")

        return ExportResult(
            filename=f"test_{func}.py",
            content=_MODULE_HEADER.format(script_name=script.name) + "\n".join(lines),
            warnings=warnings,
            media={"conftest.py": _CONFTEST.encode("utf-8")},
        )

    def _emit(self, step: Step, warnings: list[ExportWarning]) -> list[str]:
        target = _target_literal(step.target)
        if step.action is StepAction.TAP:
            return [f"await pf_device.tap({target})"]
        if step.action is StepAction.LONG_PRESS:
            return [f"await pf_device.long_press({target}, {step.duration_ms or 600})"]
        if step.action is StepAction.INPUT_TEXT:
            return [f"await pf_device.input_text({target}, {step.text!r})"]
        if step.action is StepAction.KEY:
            return [f"await pf_device.key({step.keycode})"]
        if step.action is StepAction.WAIT:
            return [f"await pf_device.sleep({(step.delay_ms or 0) / 1000})"]
        if step.action is StepAction.LAUNCH_APP:
            return [f"await pf_device.launch_app({step.package!r})"]
        if step.action is StepAction.STOP_APP:
            return [f"await pf_device.stop_app({step.package!r})"]
        if step.action is StepAction.WAIT_FOR:
            return [f"await pf_device.wait_for({target}, {step.timeout_ms})"]
        if step.action is StepAction.ASSERT:
            return [f"assert await pf_device.exists({target}), {step.name!r}"]
        if step.action is StepAction.SWIPE:
            to = step.to
            assert to is not None  # enforced by the Step validator
            return [
                f"await pf_device.swipe({target}, ({to.x}, {to.y}), "
                f"{step.duration_ms or 300})"
            ]
        if step.action is StepAction.SCREENSHOT:
            return [f"await pf_device.screenshot({step.id!r})"]
        if step.action is StepAction.SCRIPT:
            warnings.append(
                ExportWarning(
                    step.id,
                    "inline Python step emitted verbatim",
                    "review it -- it was written against the IDE's dev SDK, whose "
                    "names do not exist in the generated module",
                )
            )
            return (step.code or "").splitlines() or ["pass"]
        warnings.append(
            ExportWarning(
                step.id,
                f"action {step.action.value!r} has no pytest equivalent",
                "the step is skipped; the exported test does less than the flow",
            )
        )
        return ["pass"]


def _identifier(value: str) -> str:
    cleaned = "".join(char if char.isalnum() else "_" for char in value).strip("_")
    return cleaned.lower() or "flow"


def _target_literal(target: Target | None) -> str:
    """Render a Target as a dict literal with no helper to import."""
    if target is None:
        return "None"
    payload = target.model_dump(mode="json", exclude_none=True)
    # recorded_on is provenance for diagnosing a cross-device failure, not
    # something a runner acts on; keeping it would just add noise to every line.
    payload.pop("recorded_on", None)
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)
