"""Export to a runnable pytest module, so a flow can gate CI."""

from __future__ import annotations

from pixelforge.exporters.base import ExportResult, ExportWarning
from pixelforge.script.model import Project, Script, StepAction

__all__ = ["PytestExporter"]

_HEADER = '''"""Generated by PixelForge from {script_name!r}. Do not edit by hand.

Re-export from PixelForge after changing the flow.

Run with a device attached:
    pytest {filename} --device <serial>
"""

import pytest

pytestmark = pytest.mark.device


'''


class PytestExporter:
    name = "pytest"
    description = "A pytest module that replays the flow in CI"

    def export(self, project: Project, script: Script) -> ExportResult:
        warnings: list[ExportWarning] = []
        lines: list[str] = []
        func = _identifier(script.id)

        lines.append(f"async def test_{func}(pf_device):")
        lines.append(f'    """{script.name}"""')
        if not script.steps:
            lines.append("    pytest.skip('script has no steps')")

        for step in script.steps:
            if not step.enabled:
                lines.append(f"    # skipped (disabled): {step.name}")
                continue
            lines.append(f"    # {step.name}")
            lines.extend(f"    {line}" for line in self._emit(step, warnings))
        lines.append("")

        return ExportResult(
            filename=f"test_{func}.py",
            content=_HEADER.format(
                script_name=script.name, filename=f"test_{func}.py"
            )
            + "\n".join(lines),
            warnings=warnings,
        )

    def _emit(self, step, warnings: list[ExportWarning]) -> list[str]:
        target = f"pf.target({_target_expr(step.target)})" if step.target else "None"
        if step.action is StepAction.TAP:
            return [f"await pf_device.tap({target})"]
        if step.action is StepAction.LONG_PRESS:
            return [f"await pf_device.long_press({target}, {step.duration_ms or 600})"]
        if step.action is StepAction.INPUT_TEXT:
            return [f"await pf_device.input_text({target}, {step.text!r})"]
        if step.action is StepAction.KEY:
            return [f"await pf_device.key({step.keycode})"]
        if step.action is StepAction.WAIT:
            return [f"await pf_device.sleep({(step.delay_ms or 0) / 1000})"]
        if step.action is StepAction.LAUNCH_APP:
            return [f"await pf_device.launch_app({step.package!r})"]
        if step.action is StepAction.STOP_APP:
            return [f"await pf_device.stop_app({step.package!r})"]
        if step.action is StepAction.WAIT_FOR:
            return [f"await pf_device.wait_for({target}, timeout_ms={step.timeout_ms})"]
        if step.action is StepAction.ASSERT:
            return [f"assert await pf_device.exists({target}), {step.name!r}"]
        if step.action is StepAction.SWIPE:
            to = step.to
            return [
                f"await pf_device.swipe({target}, ({to.x}, {to.y}), "
                f"{step.duration_ms or 300})"
            ]
        if step.action is StepAction.SCREENSHOT:
            return [f"await pf_device.screenshot({step.id!r})"]
        if step.action is StepAction.SCRIPT:
            warnings.append(
                ExportWarning(
                    step.id,
                    "inline Python step emitted verbatim",
                    "review it: it was written against the IDE's dev SDK",
                )
            )
            return [line for line in (step.code or "").splitlines()]
        warnings.append(
            ExportWarning(step.id, f"action {step.action.value!r} not emitted", "skipped")
        )
        return ["pass"]


def _identifier(value: str) -> str:
    cleaned = "".join(char if char.isalnum() else "_" for char in value).strip("_")
    return cleaned.lower() or "flow"


def _target_expr(target) -> str:
    if target is None:
        return ""
    parts = []
    if target.a11y is not None:
        fields = target.a11y.model_dump(exclude_none=True)
        parts.append(f"a11y={fields!r}")
    if target.template is not None:
        parts.append(f"template={target.template.file!r}")
    if target.ocr is not None:
        parts.append(f"ocr={target.ocr.pattern!r}")
    if target.coord is not None:
        parts.append(f"coord=({target.coord.x}, {target.coord.y})")
    return ", ".join(parts)
